name: Manual Image Processing and Deployment

on:
  workflow_dispatch:

jobs:
  process-images-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up ImageMagick
      run: sudo apt-get install -y imagemagick

    - name: Process images
      run: |
        mkdir -p public/images
        for file in $(find ./src/images -type f -name '*.webp'); do
          filename=$(basename -- "$file")
          convert "$file" -resize 320x -quality 85 "public/images/${filename%.*}-320.webp"
          convert "$file" -resize 640x -quality 85 "public/images/${filename%.*}-640.webp"
          convert "$file" -resize 1280x -quality 85 "public/images/${filename%.*}-1280.webp"
          convert "$file" -resize 1920x -quality 85 "public/images/${filename%.*}-1920.webp"
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/images/
        git commit -m "images(Github Actions) add or update resized images in /public/images"
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          git pull origin ${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}
        else
          git pull origin staging
          git push origin HEAD:staging
        fi

