name: Manual Image Processing and Deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    outputs:
      root-changed: ${{ steps.filter.outputs.root }}
      portfolio-changed: ${{ steps.filter.outputs.portfolio }}
      manual-trigger: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            root:
              - 'src/images/*'
            portfolio:
              - 'src/images/portfolio/*'

  process-root-images:
    runs-on: ubuntu-latest
    needs: filter-paths
    if: needs.filter-paths.outputs.root-changed == 'true' || needs.filter-paths.outputs.manual-trigger == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up webp tools
        run: sudo apt-get install -y webp

      - name: Process root images
        run: |
          mkdir -p public/images
          for file in $(find ./src/images -maxdepth 1 -type f -name '*.webp'); do
            filename=$(basename -- "$file")
            cwebp -q 82 "$file" -resize 320 0 -o "public/images/${filename%.*}-320.webp"
            cwebp -q 82 "$file" -resize 640 0 -o "public/images/${filename%.*}-640.webp"
            cwebp -q 82 "$file" -resize 1280 0 -o "public/images/${filename%.*}-1280.webp"
            cwebp -q 85 "$file" -resize 1920 0 -o "public/images/${filename%.*}-1920.webp"
            cwebp -q 90 "$file" -resize 2560 0 -o "public/images/${filename%.*}-2560.webp"
          done

      - name: Check for changes
        id: changes_check
        run: echo "CHANGES=$(git status --porcelain | wc -l > 0)" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/images/
          git commit -m "images(Github Actions) add or update resized images in /public/images"
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          else
            git pull --rebase origin staging
            git push origin HEAD:staging

  process-portfolio-images:
    runs-on: ubuntu-latest
    needs: filter-paths
    if: needs.filter-paths.outputs.portfolio-changed == 'true' || needs.filter-paths.outputs.manual-trigger == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up webp tools
        run: sudo apt-get install -y webp

      - name: Process portfolio images
        run: |
          mkdir -p public/images/
          for file in $(find ./src/images/portfolio -type f -name '*.webp'); do
            filename=$(basename -- "$file")
            cwebp -q 70 "$file" -resize 320 0 -o "public/images/${filename%.*}-320.webp"
            cwebp -q 70 "$file" -resize 640 0 -o "public/images/${filename%.*}-640.webp"
            cwebp -q 70 "$file" -resize 1280 0 -o "public/images/${filename%.*}-1280.webp"
            cwebp -q 75 "$file" -resize 1920 0 -o "public/images/${filename%.*}-1920.webp"
            cwebp -q 80 "$file" -resize 2560 0 -o "public/images/${filename%.*}-2560.webp"
          done

      - name: Check for changes
        id: changes_check
        run: echo "CHANGES=$(git status --porcelain | wc -l > 0)" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/images/
          git commit -m "images(Github Actions) add or update resized images in /public/images/portfolio"
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          else
            git pull --rebase origin staging
            git push origin HEAD:staging
